apiVersion: v1
kind: Service
metadata:
  name: {{ include "clicc-devices.fullname" . }}
  namespace: clicc-devices{{ .Values.django.env.run_env }}
  labels:
    {{- include "clicc-devices.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.django.env.target_port | default "8000" }}
      protocol: TCP
      name: http
  selector:
    {{- include "clicc-devices.selectorLabels" . | nindent 4 }}
