# Values for clicc-devices prod.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: uclalibrary/clicc-devices
  tag: v1.0.3
  pullPolicy: Always

nameOverride: ""

fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  
ingress:
  enabled: "true"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    cert-manager.io/cluster-issuer: sectigo-acme-clusterissuer
    kubernetes.io/tls-acme: "true"

  hosts:
    - host: 'clicc-devices.library.ucla.edu'
      paths:
        - "/"
  tls:
  - secretName: clicc-devices-tls
    hosts:
      - clicc-devices.library.ucla.edu

django:
  env:
    run_env: "prod"
    debug: "false"
    allowed_hosts:
      - clicc-devices.library.ucla.edu
    csrf_trusted_origins:
      - https://clicc-devices.library.ucla.edu
    log_level: "INFO"
    db_backend: "django.db.backends.postgresql"
    db_name: "clicc_devices"
    db_user: "clicc_devices"
    db_host: "p-d-postgres.library.ucla.edu"
    db_port: 5432

  externalSecrets:
    enabled: "true"
    annotations: 
      argocd.argoproj.io/sync-wave: "-1"
    env:
      # Application database used by django
      alma_api_key: "/systems/prodrke01/clicc-devices/alma_api_key"
      db_password: "/systems/prodrke01/clicc-devices/db_password"
      django_secret_key: "/systems/prodrke01/clicc-devices/django_secret_key"

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 250m
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
