# Generated by Django 5.2.2 on 2025-08-19 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alma_set_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='clicc_devices.itemtype')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=128)),
                ('retrieved_datetime', models.DateTimeField()),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clicc_devices.set')),
            ],
        ),
    ]
